version: '3.1'
services:
    my-registry:
        ports:
            - '5000:5000'
        restart: always
        container_name: my-registry
        volumes:
            - registry:/var/lib/registry3
        image: 'registry:latest'
volumes:
  registry: