version: '3.4'

services:

  cnx.earningsanddeductions.unittest:
    image: cnxearninganddeductions_unit_tests:B${BUILD_NUMBER}
    build:
      context: .
      dockerfile: src/Services/EarningsAndDeductions/Cnx.EarningsAndDeductions.UnitTests/Dockerfile
