version: '3.4'

services:

  cnx.earningsanddeductions.unittest:
    image: my-registry:5000/cnx.earninganddeductions.unittest:B${BUILD_NUMBER}
    build:
      context: .
      dockerfile: src/Services/EarningsAndDeductions/Cnx.EarningsAndDeductions.UnitTests/Dockerfile

  cnx.notification.unittest:
    image: my-registry:5000/cnx.notification.unittest:B${BUILD_NUMBER}
    build:
      context: .
      dockerfile: src/Services/Notification/Cnx.Notification.API.UnitTests/Dockerfile
