version: '3.4'

services:
    local-registry:
        ports:
            - '5000:5000'
        restart: always
        container_name: local-registry
        volumes:
            - registry:/var/lib/registry3
        image: 'registry:latest'
volumes:
  registry: