apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cnx.earningsanddeductions.api
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: earningsanddeductions
    spec:
      containers:
      - name: cnx-earningsanddeductions-api
        image: cnx.earninganddeductions.api.19052020.2
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: EventBusConnection
          value: rabbit
        - name: EventBusUserName
          value: guest
        - name: EventBusPassword
          value: guest
        - name: MongoConnectionString
          value: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0
        - name: MongoDatabase
          value: EDEventStore
        - name: MySQLConnectionString
          value: Server=mysql.data;database=EarningsAndDeductions;user=root;password=P@ssw0rd
        - name: FilePath
          value: /app
        - name: ElasticsearchUrl
          value: http://cnx.search/api/v1/Search/search
        - name: IdentityUrl
          value: http://cnx.identity.api
        ports:
        - name: node-port
          containerPort: 80